### ISSUE TITLE
Gap around window

### ISSUE THREAD

**Issue by GammaGames** [flathub/com.prusa3d.PrusaSlicer#11]
When I run the app, the window has a gap and double titles:
![image](https://user-images.githubusercontent.com/7832163/119163445-a5e28780-ba18-11eb-80e6-3e891147741e.png)

Is this a common issue? I'm running on elementary OS

**Comment by xarbit** [comment]
haven't seen this, what type of screen are you using?

**Comment by GammaGames** [comment]
Just a regular screen, 1080p with no scaling. I wonder if it's a GTK issue? I uninstalled `org.gtk.Gtk3theme.elementary` and the gap was smaller:

![image](https://user-images.githubusercontent.com/7832163/119363090-a70af300-bc6a-11eb-81b1-cf929a1fbb53.png)

**Comment by xarbit** [comment]
@GammaGames 
Can you please install the latest beta 2.4 and let me know if your issue still remains:

Install from command line as :

`flatpak install https://dl.flathub.org/build-repo/56101/com.prusa3d.PrusaSlicer.flatpakref
`

**Comment by GammaGames** [comment]
All seems fixed! 
![image](https://user-images.githubusercontent.com/7832163/131860045-604eae53-5c9c-4d2f-aa3d-be9a75ae1fb6.png)
Love the clippy, too

**Comment by xarbit** [comment]
awesome, thanks for testing!
