### ISSUE TITLE
Unable to unmount SD card

### ISSUE THREAD

**Issue by xvalen** [flathub/com.prusa3d.PrusaSlicer#44]
**Version**
2.4.0

**Operating system type + version**
OpenSUSE Tumbleweed 20220207
Fedora 35

**Issue:**
I am unable to unmout SD card or USB stick after exporting gcode. Application shows alert that Ejecting failed. I have not found nothing useful in logs and internet. When I install prusaslicer from package manager, unmounting works. 

What could be wrong please?

**Comment by xarbit** [comment]
Does this issue still remain?

**Comment by jhaand** [comment]
Yes, the issue still persists with this flatpak.

Tested on Debiab Bookworm /  KDE 5.90.0 / Plasma 5.24.4

**Comment by kozross** [comment]
Same here.

**Comment by eliadevito** [comment]
Ubuntu snap version seem to apply a patch for this: https://github.com/ivocavalcante/PrusaSlicer-snap/blob/main/patches/use_udisks2_for_unmounting.patch maybe it can be helpful here or directly upstream.

@xarbit what do you think about it?

**Comment by xarbit** [comment]
@eliadevito  As you already seen, I added it in .. Can you test it and give feedback so we can close this ticket? Thanks

**Comment by bubnikv** [comment]
> Ubuntu snap version seem to apply a patch for this:
https://github.com/ivocavalcante/PrusaSlicer-snap/blob/main/patches/use_udisks2_for_unmounting.patch
maybe
it can be helpful here or directly upstream.

Thanks, we will look at that patch.

**Comment by xarbit** [comment]
Fixed in https://github.com/flathub/com.prusa3d.PrusaSlicer/pull/54 .. @eliadevito thanks for the good work

**Comment by jhaand** [comment]
I just installed PrusaSlicer 2.5.0. Unmounting the USB pen drive now works from PrusaSlicer.
