### ISSUE TITLE
PrusaSlicer 2.5.1 crashes when clicking 'variable layer height'

### ISSUE THREAD

**Issue by jhony1104** [flathub/com.prusa3d.PrusaSlicer#63]
PrusaSlicer crashes when clicking 'variable layer height' button in object view.

This issue is specific to the flatpack version of PrusaSlicer or at least not reproducable with the `linux-x64-GTK3` AppImage.

**Comment by bubnikv** [comment]
This issue should be fixed in PrusaSlicer 2.6.0-alpha5.
