### ISSUE TITLE
Version 2.3?

### ISSUE THREAD

**Issue by vajonam** [flathub/com.prusa3d.PrusaSlicer#7]
Just wondering when version 2.3 will show up in flatpack hub?

**Comment by xarbit** [comment]
Soon ..

**Comment by tigert** [comment]
...? :-)

**Comment by vadyalex** [comment]
I am not familiar with flatpak except of `flatpak install -y` :grin: but wonder if it is possible to automate the process after new version is released by Prusa people?

**Comment by ctron** [comment]
Any news on a newer version?
