### ISSUE TITLE
Printables.com desktop integration doesn't work

### ISSUE THREAD

**Issue by Sp4rkR4t** [flathub/com.prusa3d.PrusaSlicer#81]
Desktop integration for this flatpak version do not work on any of my systems (mint 21.2, arch, endevouros) I wish I could point to a solution but I have no clue when it comes to flatpak.

**Comment by xarbit** [comment]
Thanks for your report. 
We will look in to this : @eliadevito can you please have a look at this and activate the beta channel for the [PrusaSlicer 2.6.1-rc1](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.6.1-rc1)

**Comment by xarbit** [comment]
Should now be fixed in the beta channel and generally available for the upcoming 2.6.1 release. Thx to @eliadevito 

Will close this issue
