### ISSUE TITLE
Cannot resolve physical printer hostname over multicast DNS (*.local)

### ISSUE THREAD

**Issue by Hyperspeed1313** [flathub/com.prusa3d.PrusaSlicer#89]
I can't get PrusaSlicer to find my printer by hostname. The printer uses Fluidd/Mainsail and broadcasts its hostname over multicast dns (fluiddpi.local). Adding an entry for the printer to my network's DNS rewrites allows it to be found (assuming the DNS rewrite doesn't use the .local TLD).

I started with the default Flatpak permissions defined by Flathub, and have since thrown every flatseal setting I can at this package, but I'm still unable to resolve the hostname via mDNS using the Flatpak package - testing the hostname gets [Error 6] - could not resolve host. This is not a problem on Windows or on the AppImage.

Host OS: Fedora 38

**Comment by eliadevito** [comment]
This should be caused by a flatpak limitation tracked here [1013](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1013)

**Comment by Hyperspeed1313** [comment]
Until that issue is closed and it's still a problem, concur.
