### ISSUE TITLE
Blurry interface on Wayland

### ISSUE THREAD

**Issue by bendavis78** [flathub/com.prusa3d.PrusaSlicer#90]
See screenshot:

![image](https://github.com/flathub/com.prusa3d.PrusaSlicer/assets/324392/6cebcee3-04d2-4b50-b6cd-1b34227b8679)

I'm running Arch Linux, and have installed using flatpack.

**Comment by xarbit** [comment]
I am closing this, feel free to reopen if you still have issues.
