### ISSUE TITLE
Cannot choose language in PrusaSlicer 2.7.1

### ISSUE THREAD

**Issue by jernejp21** [flathub/com.prusa3d.PrusaSlicer#99]
I think that flatpak build went wrong somewhere. When I install flatpak from flathub, I cannot choose language other than English.

![slika](https://github.com/flathub/com.prusa3d.PrusaSlicer/assets/61543115/b7f1be25-4db6-4215-b712-37cac412f3fb)

I built my own flatpak and installed it and language selection works, but when selecting other language (Japanese for example), I get this error message.
Install command: `flatpak-builder --user --install --force-clean build-dir com.prusa3d.PrusaSlicer.yml`

![slika](https://github.com/flathub/com.prusa3d.PrusaSlicer/assets/61543115/9105177b-cf9c-4b22-b639-9ff01263b15d)

Since flatpak is in sandbox, I think locales for all supported languages should also be build. But the question is still why is only English shown.

One more thing, in `/home/<user>/.local/share/flatpak/com.prusa3d.PrusaSlicer/current/active/files/share/runtime/locale`, all folders are empty. They should have po and mo files inside.

**Comment by eliadevito** [comment]
Hi @jernejp21,
You have to enable the locale on flatpak, to do it you have to set the languages/extra-languages  key with  `flatpak config` as described here: [https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-config](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-config).

If you need help to do it, please post here the output of `flatpak config --list` command and the locale that you want to enable

**Comment by jernejp21** [comment]
@eliadevito 

Thank you for your help. Your proposal worked.
